### PR TITLE
Feature branch 1

### PR DESCRIPTION
**Pull request by tta2yta**
I have created branches with git-flow called main, develop, and feature_branch_1, and I have coded the my_enumerables module in feature_branch_1.  In that branch, I set up GitHub workflows and added linters.yml inside the .github/workflows folder and rubocop.yml in the root directory. This project consists of different ruby enumerable methods that emulate Ruby's in-built enumerable methods.

I created tests for the methods inside the main file.
All tests passed

Kindly review my code before I merge it.
Thanks in advance.

### CODE REVIEW

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Changes required:full_moon:
**Hi team!
Nice Job. The methods are well thought out and clearly written. Keep up the hard work:clap::clap:. We still need to make a few changes in the project to get it approved:muscle:.**

- [ ] #my_each returns an Enumerator if no block is given. This means it should return an enumerator. Currently, It's not returning anything. Check line 4. I expected the code to be something like this: return to_enum(:my_each) unless block_given?. 

- [ ] #my_each_with_index returns an enumerator if no block is given. Instead of returning an enumerator. It returns a LocalJumpError. Check what the yield is returning in line 30

- [ ] #my_each_with_index when a block is given when self is an array returns the array itself after calling the given block once for each element in self. It's returning nil instead of an array.

- [ ] #my_each_with_index when a block is given when self is an array behaves like #each_with_index calls the given block once for each element in self

  

- [ ] #my_each_with_index when a block is given when self is a range returns the range itself after calling the given block once for each element in self. it returns NoMethodError: undefined method `[]' for 5..50:Range. Check what the yield is returning in line 26. 

- [ ] #my_each_with_index when a block is given when self is a hash behaves like #each_with_index calls the given block once for each element in self. Currently, It's not returning the expected result. Check line 23 if it's given the expected result. I expected that line of code to return something unless block_given?

- [ ] #each_with_index calls the given block once for each element in self. It's not returning the expected result. As earlier highlighted, check if the yield is returning the expected result.

- [ ] #my_select returns an enumerator if no block is given. It's currently throwing a NoMethodError. Check if my_each is actually working inside the method.

- [ ] #my_all? returns false if the block returns false or nil::range.  It's currently throwing a NoMethodError. Refactor the method especially line 45.

- [ ] #my_all? when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern. It's returning true instead of false. Refactor the method to account for this.

- [ ] #my_any? returns false if the block ever returns a value false or nil::range. It's throwing an undefined method 'empty'. Check line 94, empty? is not defined.

- [ ] #my_any? when a pattern other than Regex or a Class is given returns true if any of the collection matches the pattern. Expected true, but return false.

- [ ] #my_none? returns false if the block ever returns true for all elements::range. Throws an undefined method 'empty?'. 

- [ ] #my_none? when a pattern other than Regex or a Class is given returns false only if one of the collection matches the pattern. Expected false, got true.

- [ ] #my_map returns an Enumerator if no block is given. Currently, It's not returning an enumerator. Check if my_each is working as expected

- [ ] #my_map executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.  ArgumentError: wrong number of arguments (given 1, expected 0).

- [ ] #my_inject raises a "LocalJumpError" when no block or argument is given. expected LocalJumpError but nothing was raised. Kindly check if the method covers this test.

- [ ] The test file(main.rb) is not required. The testing for this project will be provided by Microverse through the Tse.

- [ ] Add the second author in the readme. The project was submitted as a collaborative project.

Make the above-required changes and when you are ready, request another review.
Kindly drop your questions :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy Coding:blush:
Eric Enaburekhan.

**Comment by tta2yta** [comment]
Hello. Thank you for your review.  I have corrected all the points you mentioned. for the point you mentioned " Add the second author in the readme. The project was submitted as a collaborative project.",  this project has an option whether you can do solo or collaboration that's why I did it as a solo project. 

Kindly review my code before I merge it.
Thanks in advance.

**Review by Georjane — CHANGES_REQUESTED** [review]
## Status: Changes Required 🛑 🔧 
### Hi there Team ✋🏽 
Great job so far. However, we have a couple of test that are not yet passing:

- [ ] enumerables #my_each_with_index when a block is given when self is an array behaves like #each_with_index calls the given block once for each element in self
- [ ] enumerables #my_each_with_index when a block is given when self is a range behaves like #each_with_index calls the given block once for each element in self
- [ ] enumerables #my_each_with_index when a block is given when self is a hash behaves like #each_with_index calls the given block once for each element in self
- [ ] enumerables #my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
- [ ] enumerables #my_all? when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern
- [ ]  enumerables #my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
- [ ] enumerables #my_any? when a pattern other than Regex or a Class is given returns true if any of the collection matches the pattern
- [ ] enumerables #my_none? when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
- [ ] enumerables #my_none? when a pattern other than Regex or a Class is given returns false only if one of the collection matches the pattern
- [ ] enumerables #my_map executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.

Please fix the above issues and submit for another code review.

_Feel free to reach out to me on Slack if you have any questions, Witah Georjane_ 🤝 
Good luck on your project and Happy Coding 💻 

**Witah Georjane
Code Reviewer at Microverse Inc
[portfolio](https://witahgeorjane.tech/) | [linkedIn](https://www.linkedin.com/in/witah-georjane/)**

**Review by mke2111 — CHANGES_REQUESTED** [review]
# **STATUS: CHANGES REQUIRED 🔴 ⚠️** 

## Hey @tta2yta, 👋🏽 
 **Thank you for the good job you got going on and making all the requested changes. The enumerable methods run just fine and almost pass all test cases.**

## REQUIRED CHANGES 🟥 🟨 🟢 

- [ ] Kindly fix all the rubocop errors, I have one offense detected locally.
- [ ] Adjust your readme file to perfectly suit your enumerable project. Make your cloning procedure more descriptive and remove the installing section since we are not using `npm install` for this project.

###  `TypeError` that requires a class or module is raised for all these methods.
- [ ] ` my_all?` when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern.
- [ ] `my_all?` when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern.
- [ ] `my_any?` when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
- [ ] `my_any?` when a pattern other than Regex or a Class is given returns true if any of the collection matches the pattern
- [ ] `my_none?` when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
- [ ] `my_none?` when a pattern other than Regex or a Class is given returns false only if one of the collection matches the pattern


- [ ] For this method, `my_map` should execute only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum. Your method throws an argument error when I pass one argument to it, instead expects zero arguments.


**Kindly make all the requested changes and submit another CRR. 👍🏽** 

## Cheers!! 🍹 & Happy Coding.

# Reach me on slack for a chitchat 🆘  **Roy Mukuye**

**Comment by tta2yta** [comment]
Hello. Thank you for your review. I have corrected all the points you mentioned.

Kindly review my code before I merge it.
Thanks in advance.

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Changes Requested :skull:

Hello Developer, 👋 

Thank you for requesting another review. You have done a great job so far. If you can make the changes requested below I think your project would be ready to approve. 

- [ ]  #my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Integer

- [ ]  #my_all? when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric

- [ ]  #my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

- [ ]  #my_any? when a class is passed as an argument returns true if at least one of the collection is a member of such class::Numeric

- [ ] #my_any? when a pattern other than Regex or a Class is given returns true if any of the collection matches the pattern

- [ ] #my_none? when a pattern other than Regex or a Class is given returns false only if one of the collection matches the pattern

- [ ] #my_map executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.

Please make the changes and request another review. 

Thank you again 🙈 

_If you have a question please reach out to me on slack 👍  @arslanbisharat_

**Best,
Arslan Bisharat**

**Comment by tta2yta** [comment]
Hello. Thank you for your review. I have corrected all the points you mentioned.

Kindly review my code before I merge it.
Thanks in advance.

**Comment by mimipeshy** [comment]
### STATUS :APPROVED :partying_face: 

Hey there @tta2yta  :wave: :wave:  good job on working on the requested changes. This project is therefore approved. Go ahead and merge. All the best in the next milestones :man_technologist: 

Regards
Peris Ndanu

**Comment by tta2yta** [comment]
Good Job.

**Pull request merged**
